name: Playwright Tests + Trigger Repos

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

  trigger-repos:
    name: Trigger Dependent Repos
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Trigger Repo2
        run: |
          curl -X POST \
          https://api.github.com/repos/Arfaa49/Repo-2/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO1_TOKEN }}" \
          -d '{"event_type":"run-tests"}'

      - name: Trigger Repo3
        run: |
          curl -X POST \
          https://api.github.com/repos/Arfaa49/Repo-3/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO1_TOKEN }}" \
          -d '{"event_type":"run-tests"}'

      - name: Trigger Repo4
        run: |
          curl -X POST \
          https://api.github.com/repos/Arfaa49/Repo-4/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO1_TOKEN }}" \
          -d '{"event_type":"run-tests"}'
